<!DOCTYPE html>
<html>
    <head>
        <title>VR Contact</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="CSS/style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="wrapper">
        <nav>
            <div id="metanavi">
                <a href="#">Anmelden</a>
            </div>
            <h1><span>V</span>irtual <span>R</span>evolution</h1>
            <ul>
                <li><a href="?controller=Welcome&do=showWelcome">Willkommen</a></li>
                <li><a href="#">Projekte</a></li>
                <li><a href="#">Workshops</a></li>
                <li><a href="?controller=Contact&do=showContactForm">Kontakt</a></li>
                
            </ul>
        </nav>
        
        <main>